# -*- mode: makefile-gmake; coding: utf-8-unix; -*-

#
# Makefileのテンプレート
#

CC = gcc
CFLAGS = -g -Wall -O2
LDFLAGS = -g -Wall

# 明示的に POSIX.1-2001 を有効にする必要がある場合、以下を有効にする
#
# CPPFLAGS = -DPOSIX_C_SOURCE=200112L

# common.mk,src,include,toolsがあるトップディレクトリを指定する。
#
TOP_DIR = ../atk2

# カレントディレクトリに、Embedded Coderが生成したファイルがないなら、
# Embedded Coderが生成したモデルのコードのパスを指定する
# (これを元にインクルードパスの追加やソースを探すvpath設定が行われる)
#
# ATK2_MODEL_DIR =

# Windows環境では .exe を指定することになる(Windows環境では動作未確認)
#
# EXE_POSTFIX =

# ABREXのYAMLファイル(未定義の場合 testout.yaml になる)
#
# ATK2_ABREX_YAML =

# ATK2のmain関数のソースファイルの指定
# (未定義の場合は ambp_main.c になる)
#
# ATK2_SRC_MAIN =

# その他のATK2のソース(未定義の場合は counter_handler.c になる)
#
# ATK2_SRC_OTHER =

# CSPトランスレータが生成したソースと、モデルに必要なソースがあれば追加
# する(未定義の場合 testout.c になる)
#
# ATK2_SRCS =

# 実行プログラム名。ただしファイル名ではなく、makeのターゲットである。
# (未定義の場合は testout)
#
# ATK2_PROGRAM =

# 実行トレース用の生成ヘッダファイル名指定(未定義の場合 testout_trace.h)
# (空にすると生成されない)
#
# ATK2_TRACE_HDR =

# clean で削除するファイルの追加
# ($(ATK2_PROGRAM)$(EXE_POSTFIX), および対象の %.o は自動的に追加される)
#
# ATK2_CLEAN_FILES =

# distclean/realclean で削除するファイルの追加
# (Os_Lcfg.[ch], $(ATK2_TRACE_HDR), *.d は自動的に追加される)
#
# ATK2_DISTCLEAN_FILES =

# 擬似ターゲットの追加
# (all abrex program clean realclean distclean depend は自動的に追加される)
#
# ATK2_PHONY_TARGETS =

# プログラムのビルド前に実行したいターゲットがある場合、ここでそのター
# ゲットをallの依存ターゲットとして追加する。
# その場合、ATK2_PHONY_TARGETS にも利用者のターゲットを追加する。
#
# all:

# もしもデフォルトゴールのallをどうしても使用できず、別の何かに変更する
# 必要がある場合は、そのターゲットを .DEFAULT_GOAL に設定する。
#
# .DEFAULT_GOAL :=

include $(TOP_DIR)/common.mk

# プログラムそのものに関連し、プログラムのビルド前に実行する必要のある
# ターゲットは、ここにprogramの依存ターゲットとして追加する。
#
# ただし、ATK2_PHONY_TARGETS への追加は、common.mkのインクルード前に行
# う必要がある。
#
# program:

# プログラムのビルド後に実行したいターゲットがある場合、ここでそのター
# ゲットをallの依存ターゲットとして追加する。
#
# ただし、ATK2_PHONY_TARGETS への追加は、common.mkのインクルード前に行
# う必要がある。
#
# all:
